name: build
on:
  push:

jobs:
  test:
    needs: build 
    name: Workflow test
    runs-on: ubuntu-22.04
    steps:
      - name: Start workflow
        uses: monun-docs/surf@v1.7
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build workflow
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: rm -rf dist
      - run: npm i @vercel/ncc -g
      - run: npm install
      - run: npm run package
      - name: Get Version
        run: echo '::set-output name=PACKAGE_VERSION::$(echo | node version.js | tr -d "[:blank:]")'
        id: get-package-version
      - name: Commit
        continue-on-error: true
        run: |
          git config --global user.name 'MonunDocs Bot'
          git config --global user.email 'admin@monun.me'
          git add .
          git commit -m "Build"
          git tag v${{ steps.get-package-version.outputs.PACKAGE_VERSION }}
          git push origin main --tag
