name: test
on:
  push:
  # schedule:
  # - cron: '*/5 * * * *'

jobs:
  test:
    needs: build 
    name: Workflow test
    runs-on: ubuntu-22.04
    steps:
      - name: Start workflow
        uses: monun-docs/surf@v0.1
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}